# Generated by Django 3.0.4 on 2020-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='topic',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
